global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "py_app"
    static_configs:
    - targets: ["collector:9200"]

  # - job_name: "cadvisor"
  #   metrics_path: /containers
  #   static_configs:
  #   - targets: ["cadvisor:9001"]
